### ISSUE TITLE
Component Template Matching Deletion and ReAddition

### ISSUE THREAD

**Issue by umesh-timalsina** [symbench/scm#71]
#69 removed the duplicates for hand labeled components. However, there is one other aspect of duplication that I think we need to cover:

1. User Creates annotation and the template matching happens
2. User deletes the original hand created annotation, but decides to keep agent generated ones (See #61/#63)
3. User re-adds the original annotation by hand. 

This results in the following situation:

![image](https://user-images.githubusercontent.com/11476842/121687686-3fd1a900-ca88-11eb-89b7-85702becdc47.png)

The question now is should be be smart about these cases as well? A possible resolution here is sending all existing annotations in the `POST` body while doing the template matching and using the technique in #69 for weeding out duplicates, but should we even try to handle this case?

**Comment by brollb** [comment]
Good question. Sending all the annotations is probably a good idea. It might be possible for this to arise when hand labeling similar components that both match a third component. (This isn't entirely obvious that it could happen since it depends on the transitivity of the template matching similarity function. It seems unlikely but I am wondering if there is an edge case where it occurs.)
